version: '3'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=smartfarm
      - POSTGRES_PASSWORD=smartfarm123
      - POSTGRES_DB=smartfarm
    ports:
      - "5432:5432"

  smart-farm-mosquitto:
    container_name: smart-farm-mosquitto
    restart: always
    build:
      context: SmartFarm-MOSQUITTO
      dockerfile: Dockerfile
    expose:
      - "1883"
      - "9001"
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      - MOSQUITTO_USERNAME=smartfarm
      - MOSQUITTO_PASSWORD=smartfarm123
    volumes:
      - ./SmartFarm-MOSQUITTO/config:/mosquitto/config
      - ./SmartFarm-MOSQUITTO/log:/mosquitto/log
      - ./SmartFarm-MOSQUITTO/data:/mosquitto/data

  smart-farm-middleware:
    container_name: smart-farm-middleware
    restart: always
    build:
      context: SmartFarm-MIDDLEWARE
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    links:
      - db
    depends_on:
      - db
      - smart-farm-mosquitto
    profiles:
      - donotstart

  smart-farm-api:
    container_name: smart-farm-api
    restart: always
    build:
      context: SmartFarm-API
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    links:
      - db
    depends_on:
      - db

  smart-farm-web:
    container_name: smart-farm-web
    build:
      context: SmartFarm-WEB
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - smart-farm-api
