version: '3'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=smartfarm
      - POSTGRES_PASSWORD=smartfarm123
      - POSTGRES_DB=smartfarm
    ports:
      - "5432:5432"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6
    restart: always
    # network_mode: host
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data:/mosquitto/data
    ports:
      - 1883:1883
      - 9001:9001

  smart-farm-middleware:
    container_name: smart-farm-middleware
    restart: always
    build:
      context: SmartFarm-MIDDLEWARE
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    links:
      - db
    depends_on:
      - db
      - mosquitto

  smart-farm-api:
    container_name: smart-farm-api
    restart: always
    build:
      context: SmartFarm-API
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    links:
      - db
    depends_on:
      - db

  smart-farm-web:
    container_name: smart-farm-web
    build:
      context: SmartFarm-WEB
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - smart-farm-api